apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"ingress.kubernetes.io/ssl-redirect":"true","kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/rewrite-target":"/nb/"},"name":"des-labs-jup","namespace":"jupyter-lsst"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"jld-hub","servicePort":8000},"path":"/nb/"}]}}]}}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /nb/
  creationTimestamp: 2018-04-17T16:45:45Z
  generation: 1
  name: des-labs-jup
  namespace: jupyter-lsst
  resourceVersion: "266017"
  selfLink: /apis/extensions/v1beta1/namespaces/jupyter-lsst/ingresses/des-labs-jup
  uid: c5ffa89e-425e-11e8-bd2a-b4969110fa00
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: jld-hub
          servicePort: 8000
        path: /nb/
status:
  loadBalancer:
    ingress:
    - {}
