apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"welcome-ingress","namespace":"default"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"welcome","servicePort":80},"path":"/"}]}}]}}
  creationTimestamp: 2018-04-17T16:50:28Z
  generation: 1
  name: welcome-ingress
  namespace: default
  resourceVersion: "266997"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/welcome-ingress
  uid: 6f2ac498-425f-11e8-bd2a-b4969110fa00
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: welcome
          servicePort: 80
        path: /
status:
  loadBalancer:
    ingress:
    - {}
